### ISSUE TITLE
SVProgressHUDMaskType.gradient doesn't`t work on Swift3?

### ISSUE THREAD

**Issue by lutetium71** [SVProgressHUD/SVProgressHUD#719]
Hi,

I set SVProgressHUD.setDefaultMaskType(.gradient). But the background don't become gradient.

Xcode: 8.2.1
SVProgressHUD: 2.1.2

![wechatimg1](https://cloud.githubusercontent.com/assets/1246347/22188619/0ae8cabc-e152-11e6-87b5-ba91ec97a598.jpeg)

**Comment by madurangae** [comment]
I'm also having the same issue. Version is 2.1.2

**Comment by xrelative** [comment]
Me too, same version

**Comment by NOlivNeto** [comment]
I'm also having this issue. Version 2.1.2. Any news @honkmaster @juliensaad ?

**Comment by honkmaster** [comment]
Should be working again.

**Comment by JohnEstropia** [comment]
@honkmaster On which version is it working? The podspec on the master branch seem to still be on 2.1.2 (which the original issue was reported with)

**Comment by honkmaster** [comment]
Recent master, i will push to cocoapods an update soon.

**Comment by ammadakhtar** [comment]
@honkmaster still doesnt work with cocoapods.....Have u pushed an update to cocapods??

**Comment by sgerardi** [comment]
Also still seeing this issue.

**Comment by NOlivNeto** [comment]
Use `pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'` by now

**Comment by ammadakhtar** [comment]
Thanks @NOlivNeto  works this way (Y)

**Comment by pepejeria** [comment]
Any plans to do a new release soon including this?

**Comment by ammadakhtar** [comment]
@honkmaster  as @NOlivNeto said u can use 
pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git' in your PodFile by now to get it working until its being added

**Comment by honkmaster** [comment]
CocoaPods will come soon, @ammadakhtar is right until then.
